import {KeyValue} from "./types.ts";

export const iso2name: KeyValue = {
    "ABW": "Aruba",
    "AFG": "Afghanistan",
    "AGO": "Angola",
    "AIA": "Anguilla",
    "ALA": "Åland Islands",
    "ALB": "Albania",
    "AND": "Andorra",
    "ARE": "United Arab Emirates",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ASM": "American Samoa",
    "ATA": "Antarctica",
    "ATF": "French Southern Territories",
    "ATG": "Antigua and Barbuda",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",
    "BES": "Bonaire, Sint Eustatius and Saba",
    "BFA": "Burkina Faso",
    "BGD": "Bangladesh",
    "BGR": "Bulgaria",
    "BHR": "Bahrain",
    "BHS": "Bahamas",
    "BIH": "Bosnia and Herzegovina",
    "BLM": "Saint Barthélemy",
    "BLR": "Belarus",
    "BLZ": "Belize",
    "BMU": "Bermuda",
    "BOL": "Bolivia, Plurinational State of",
    "BRA": "Brazil",
    "BRB": "Barbados",
    "BRN": "Brunei Darussalam",
    "BTN": "Bhutan",
    "BVT": "Bouvet Island",
    "BWA": "Botswana",
    "CAF": "Central African Republic",
    "CAN": "Canada",
    "CCK": "Cocos (Keeling) Islands",
    "CHE": "Switzerland",
    "CHL": "Chile",
    "CHN": "China",
    "CIV": "Côte d'Ivoire",
    "CMR": "Cameroon",
    "COD": "Congo, Democratic Republic of the",
    "COG": "Congo",
    "COK": "Cook Islands",
    "COL": "Colombia",
    "COM": "Comoros",
    "CPV": "Cabo Verde",
    "CRI": "Costa Rica",
    "CUB": "Cuba",
    "CUW": "Curaçao",
    "CXR": "Christmas Island",
    "CYM": "Cayman Islands",
    "CYP": "Cyprus",
    "CZE": "Czechia",
    "DEU": "Germany",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DNK": "Denmark",
    "DOM": "Dominican Republic",
    "DZA": "Algeria",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "ERI": "Eritrea",
    "ESH": "Western Sahara",
    "ESP": "Spain",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FIN": "Finland",
    "FJI": "Fiji",
    "FLK": "Falkland Islands (Malvinas)",
    "FRA": "France",
    "FRO": "Faroe Islands",
    "FSM": "Micronesia, Federated States of",
    "GAB": "Gabon",
    "GBR": "United Kingdom",
    "GEO": "Georgia",
    "GGY": "Guernsey",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GIN": "Guinea",
    "GLP": "Guadeloupe",
    "GMB": "Gambia",
    "GNB": "Guinea-Bissau",
    "GNQ": "Equatorial Guinea",
    "GRC": "Greece",
    "GRD": "Grenada",
    "GRL": "Greenland",
    "GTM": "Guatemala",
    "GUF": "French Guiana",
    "GUM": "Guam",
    "GUY": "Guyana",
    "HKG": "Hong Kong",
    "HMD": "Heard Island and McDonald Islands",
    "HND": "Honduras",
    "HRV": "Croatia",
    "HTI": "Haiti",
    "HUN": "Hungary",
    "IDN": "Indonesia",
    "IMN": "Isle of Man",
    "IND": "India",
    "IOT": "British Indian Ocean Territory",
    "IRL": "Ireland",
    "IRN": "Iran, Islamic Republic of",
    "IRQ": "Iraq",
    "ISL": "Iceland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JEY": "Jersey",
    "JOR": "Jordan",
    "JPN": "Japan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KGZ": "Kyrgyzstan",
    "KHM": "Cambodia",
    "KIR": "Kiribati",
    "KNA": "Saint Kitts and Nevis",
    "KOR": "South Korea",
    "KWT": "Kuwait",
    "LAO": "Lao People's Democratic Republic",
    "LBN": "Lebanon",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LCA": "Saint Lucia",
    "LIE": "Liechtenstein",
    "LKA": "Sri Lanka",
    "LSO": "Lesotho",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "LVA": "Latvia",
    "MAC": "Macao",
    "MAF": "Saint Martin (French part)",
    "MAR": "Morocco",
    "MCO": "Monaco",
    "MDA": "Moldova, Republic of",
    "MDG": "Madagascar",
    "MDV": "Maldives",
    "MEX": "Mexico",
    "MHL": "Marshall Islands",
    "MKD": "North Macedonia",
    "MLI": "Mali",
    "MLT": "Malta",
    "MMR": "Myanmar",
    "MNE": "Montenegro",
    "MNG": "Mongolia",
    "MNP": "Northern Mariana Islands",
    "MOZ": "Mozambique",
    "MRT": "Mauritania",
    "MSR": "Montserrat",
    "MTQ": "Martinique",
    "MUS": "Mauritius",
    "MWI": "Malawi",
    "MYS": "Malaysia",
    "MYT": "Mayotte",
    "NAM": "Namibia",
    "NCL": "New Caledonia",
    "NER": "Niger",
    "NFK": "Norfolk Island",
    "NGA": "Nigeria",
    "NIC": "Nicaragua",
    "NIU": "Niue",
    "NLD": "Netherlands, Kingdom of the",
    "NOR": "Norway",
    "NPL": "Nepal",
    "NRU": "Nauru",
    "NZL": "New Zealand",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PCN": "Pitcairn",
    "PER": "Peru",
    "PHL": "Philippines",
    "PLW": "Palau",
    "PNG": "Papua New Guinea",
    "POL": "Poland",
    "PRI": "Puerto Rico",
    "PRK": "North Korea",
    "PRT": "Portugal",
    "PRY": "Paraguay",
    "PSE": "Palestine, State of",
    "PYF": "French Polynesia",
    "QAT": "Qatar",
    "REU": "Réunion",
    "ROU": "Romania",
    "RUS": "Russian Federation",
    "RWA": "Rwanda",
    "SAU": "Saudi Arabia",
    "SDN": "Sudan",
    "SEN": "Senegal",
    "SGP": "Singapore",
    "SGS": "South Georgia and the South Sandwich Islands",
    "SHN": "Saint Helena, Ascension and Tristan da Cunha",
    "SJM": "Svalbard and Jan Mayen",
    "SLB": "Solomon Islands",
    "SLE": "Sierra Leone",
    "SLV": "El Salvador",
    "SMR": "San Marino",
    "SOM": "Somalia",
    "SPM": "Saint Pierre and Miquelon",
    "SRB": "Serbia",
    "SSD": "South Sudan",
    "STP": "Sao Tome and Principe",
    "SUR": "Suriname",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SWE": "Sweden",
    "SWZ": "Eswatini",
    "SXM": "Sint Maarten (Dutch part)",
    "SYC": "Seychelles",
    "SYR": "Syrian Arab Republic",
    "TCA": "Turks and Caicos Islands",
    "TCD": "Chad",
    "TGO": "Togo",
    "THA": "Thailand",
    "TJK": "Tajikistan",
    "TKL": "Tokelau",
    "TKM": "Turkmenistan",
    "TLS": "Timor-Leste",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Türkiye",
    "TUV": "Tuvalu",
    "TWN": "Taiwan, Province of China",
    "TZA": "Tanzania, United Republic of",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "UMI": "United States Minor Outlying Islands",
    "URY": "Uruguay",
    "USA": "United States of America",
    "UZB": "Uzbekistan",
    "VAT": "Holy See",
    "VCT": "Saint Vincent and the Grenadines",
    "VEN": "Venezuela, Bolivarian Republic of",
    "VGB": "Virgin Islands (British)",
    "VIR": "Virgin Islands (U.S.)",
    "VNM": "Viet Nam",
    "VUT": "Vanuatu",
    "WLF": "Wallis and Futuna",
    "WSM": "Samoa",
    "XXX": "Unknown",
    "YEM": "Yemen",
    "ZAF": "South Africa",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe"
}

export const iso2code: KeyValue = {
    "ABW": "533",
    "AFG": "004",
    "AGO": "024",
    "AIA": "660",
    "ALA": "248",
    "ALB": "008",
    "AND": "020",
    "ARE": "784",
    "ARG": "032",
    "ARM": "051",
    "ASM": "016",
    "ATA": "010",
    "ATF": "260",
    "ATG": "028",
    "AUS": "036",
    "AUT": "040",
    "AZE": "031",
    "BDI": "108",
    "BEL": "056",
    "BEN": "204",
    "BES": "535",
    "BFA": "854",
    "BGD": "050",
    "BGR": "100",
    "BHR": "048",
    "BHS": "044",
    "BIH": "070",
    "BLM": "652",
    "BLR": "112",
    "BLZ": "084",
    "BMU": "060",
    "BOL": "068",
    "BRA": "076",
    "BRB": "052",
    "BRN": "096",
    "BTN": "064",
    "BVT": "074",
    "BWA": "072",
    "CAF": "140",
    "CAN": "124",
    "CCK": "166",
    "CHE": "756",
    "CHL": "152",
    "CHN": "156",
    "CIV": "384",
    "CMR": "120",
    "COD": "180",
    "COG": "178",
    "COK": "184",
    "COL": "170",
    "COM": "174",
    "CPV": "132",
    "CRI": "188",
    "CUB": "192",
    "CUW": "531",
    "CXR": "162",
    "CYM": "136",
    "CYP": "196",
    "CZE": "203",
    "DEU": "276",
    "DJI": "262",
    "DMA": "212",
    "DNK": "208",
    "DOM": "214",
    "DZA": "012",
    "ECU": "218",
    "EGY": "818",
    "ERI": "232",
    "ESH": "732",
    "ESP": "724",
    "EST": "233",
    "ETH": "231",
    "FIN": "246",
    "FJI": "242",
    "FLK": "238",
    "FRA": "250",
    "FRO": "234",
    "FSM": "583",
    "GAB": "266",
    "GBR": "826",
    "GEO": "268",
    "GGY": "831",
    "GHA": "288",
    "GIB": "292",
    "GIN": "324",
    "GLP": "312",
    "GMB": "270",
    "GNB": "624",
    "GNQ": "226",
    "GRC": "300",
    "GRD": "308",
    "GRL": "304",
    "GTM": "320",
    "GUF": "254",
    "GUM": "316",
    "GUY": "328",
    "HKG": "344",
    "HMD": "334",
    "HND": "340",
    "HRV": "191",
    "HTI": "332",
    "HUN": "348",
    "IDN": "360",
    "IMN": "833",
    "IND": "356",
    "IOT": "086",
    "IRL": "372",
    "IRN": "364",
    "IRQ": "368",
    "ISL": "352",
    "ISR": "376",
    "ITA": "380",
    "JAM": "388",
    "JEY": "832",
    "JOR": "400",
    "JPN": "392",
    "KAZ": "398",
    "KEN": "404",
    "KGZ": "417",
    "KHM": "116",
    "KIR": "296",
    "KNA": "659",
    "KOR": "410",
    "KWT": "414",
    "LAO": "418",
    "LBN": "422",
    "LBR": "430",
    "LBY": "434",
    "LCA": "662",
    "LIE": "438",
    "LKA": "144",
    "LSO": "426",
    "LTU": "440",
    "LUX": "442",
    "LVA": "428",
    "MAC": "446",
    "MAF": "663",
    "MAR": "504",
    "MCO": "492",
    "MDA": "498",
    "MDG": "450",
    "MDV": "462",
    "MEX": "484",
    "MHL": "584",
    "MKD": "807",
    "MLI": "466",
    "MLT": "470",
    "MMR": "104",
    "MNE": "499",
    "MNG": "496",
    "MNP": "580",
    "MOZ": "508",
    "MRT": "478",
    "MSR": "500",
    "MTQ": "474",
    "MUS": "480",
    "MWI": "454",
    "MYS": "458",
    "MYT": "175",
    "NAM": "516",
    "NCL": "540",
    "NER": "562",
    "NFK": "574",
    "NGA": "566",
    "NIC": "558",
    "NIU": "570",
    "NLD": "528",
    "NOR": "578",
    "NPL": "524",
    "NRU": "520",
    "NZL": "554",
    "OMN": "512",
    "PAK": "586",
    "PAN": "591",
    "PCN": "612",
    "PER": "604",
    "PHL": "608",
    "PLW": "585",
    "PNG": "598",
    "POL": "616",
    "PRI": "630",
    "PRK": "408",
    "PRT": "620",
    "PRY": "600",
    "PSE": "275",
    "PYF": "258",
    "QAT": "634",
    "REU": "638",
    "ROU": "642",
    "RUS": "643",
    "RWA": "646",
    "SAU": "682",
    "SDN": "729",
    "SEN": "686",
    "SGP": "702",
    "SGS": "239",
    "SHN": "654",
    "SJM": "744",
    "SLB": "090",
    "SLE": "694",
    "SLV": "222",
    "SMR": "674",
    "SOM": "706",
    "SPM": "666",
    "SRB": "688",
    "SSD": "728",
    "STP": "678",
    "SUR": "740",
    "SVK": "703",
    "SVN": "705",
    "SWE": "752",
    "SWZ": "748",
    "SXM": "534",
    "SYC": "690",
    "SYR": "760",
    "TCA": "796",
    "TCD": "148",
    "TGO": "768",
    "THA": "764",
    "TJK": "762",
    "TKL": "772",
    "TKM": "795",
    "TLS": "626",
    "TON": "776",
    "TTO": "780",
    "TUN": "788",
    "TUR": "792",
    "TUV": "798",
    "TWN": "158",
    "TZA": "834",
    "UGA": "800",
    "UKR": "804",
    "UMI": "581",
    "URY": "858",
    "USA": "840",
    "UZB": "860",
    "VAT": "336",
    "VCT": "670",
    "VEN": "862",
    "VGB": "092",
    "VIR": "850",
    "VNM": "704",
    "VUT": "548",
    "WLF": "876",
    "WSM": "882",
    "XXX": "000",
    "YEM": "887",
    "ZAF": "710",
    "ZMB": "894",
    "ZWE": "716"
}

export const code2shortIso: KeyValue = {
    "533": "AW",
    "004": "AF",
    "024": "AO",
    "660": "AI",
    "248": "AX",
    "008": "AL",
    "020": "AD",
    "784": "AE",
    "032": "AR",
    "051": "AM",
    "016": "AS",
    "010": "AQ",
    "260": "TF",
    "028": "AG",
    "036": "AU",
    "040": "AT",
    "031": "AZ",
    "108": "BI",
    "056": "BE",
    "204": "BJ",
    "535": "BQ",
    "854": "BF",
    "050": "BD",
    "100": "BG",
    "048": "BH",
    "044": "BS",
    "070": "BA",
    "652": "BL",
    "112": "BY",
    "084": "BZ",
    "060": "BM",
    "068": "BO",
    "076": "BR",
    "052": "BB",
    "096": "BN",
    "064": "BT",
    "074": "BV",
    "072": "BW",
    "140": "CF",
    "124": "CA",
    "166": "CC",
    "756": "CH",
    "152": "CL",
    "156": "CN",
    "384": "CI",
    "120": "CM",
    "180": "CD",
    "178": "CG",
    "184": "CK",
    "170": "CO",
    "174": "KM",
    "132": "CV",
    "188": "CR",
    "192": "CU",
    "531": "CW",
    "162": "CX",
    "136": "KY",
    "196": "CY",
    "203": "CZ",
    "276": "DE",
    "262": "DJ",
    "212": "DM",
    "208": "DK",
    "214": "DO",
    "012": "DZ",
    "218": "EC",
    "818": "EG",
    "232": "ER",
    "732": "EH",
    "724": "ES",
    "233": "EE",
    "231": "ET",
    "246": "FI",
    "242": "FJ",
    "238": "FK",
    "250": "FR",
    "234": "FO",
    "583": "FM",
    "266": "GA",
    "826": "GB",
    "268": "GE",
    "831": "GG",
    "288": "GH",
    "292": "GI",
    "324": "GN",
    "312": "GP",
    "270": "GM",
    "624": "GW",
    "226": "GQ",
    "300": "GR",
    "308": "GD",
    "304": "GL",
    "320": "GT",
    "254": "GF",
    "316": "GU",
    "328": "GY",
    "344": "HK",
    "334": "HM",
    "340": "HN",
    "191": "HR",
    "332": "HT",
    "348": "HU",
    "360": "ID",
    "833": "IM",
    "356": "IN",
    "086": "IO",
    "372": "IE",
    "364": "IR",
    "368": "IQ",
    "352": "IS",
    "376": "IL",
    "380": "IT",
    "388": "JM",
    "832": "JE",
    "400": "JO",
    "392": "JP",
    "398": "KZ",
    "404": "KE",
    "417": "KG",
    "116": "KH",
    "296": "KI",
    "659": "KN",
    "410": "KR",
    "414": "KW",
    "418": "LA",
    "422": "LB",
    "430": "LR",
    "434": "LY",
    "662": "LC",
    "438": "LI",
    "144": "LK",
    "426": "LS",
    "440": "LT",
    "442": "LU",
    "428": "LV",
    "446": "MO",
    "663": "MF",
    "504": "MA",
    "492": "MC",
    "498": "MD",
    "450": "MG",
    "462": "MV",
    "484": "MX",
    "584": "MH",
    "807": "MK",
    "466": "ML",
    "470": "MT",
    "104": "MM",
    "499": "ME",
    "496": "MN",
    "580": "MP",
    "508": "MZ",
    "478": "MR",
    "500": "MS",
    "474": "MQ",
    "480": "MU",
    "454": "MW",
    "458": "MY",
    "175": "YT",
    "516": "NA",
    "540": "NC",
    "562": "NE",
    "574": "NF",
    "566": "NG",
    "558": "NI",
    "570": "NU",
    "528": "NL",
    "578": "NO",
    "524": "NP",
    "520": "NR",
    "554": "NZ",
    "512": "OM",
    "586": "PK",
    "591": "PA",
    "612": "PN",
    "604": "PE",
    "608": "PH",
    "585": "PW",
    "598": "PG",
    "616": "PL",
    "630": "PR",
    "408": "KP",
    "620": "PT",
    "600": "PY",
    "275": "PS",
    "258": "PF",
    "634": "QA",
    "638": "RE",
    "642": "RO",
    "643": "RU",
    "646": "RW",
    "682": "SA",
    "729": "SD",
    "686": "SN",
    "702": "SG",
    "239": "GS",
    "654": "SH",
    "744": "SJ",
    "090": "SB",
    "694": "SL",
    "222": "SV",
    "674": "SM",
    "706": "SO",
    "666": "PM",
    "688": "RS",
    "728": "SS",
    "678": "ST",
    "740": "SR",
    "703": "SK",
    "705": "SI",
    "752": "SE",
    "748": "SZ",
    "534": "SX",
    "690": "SC",
    "760": "SY",
    "796": "TC",
    "148": "TD",
    "768": "TG",
    "764": "TH",
    "762": "TJ",
    "772": "TK",
    "795": "TM",
    "626": "TL",
    "776": "TO",
    "780": "TT",
    "788": "TN",
    "792": "TR",
    "798": "TV",
    "158": "TW",
    "834": "TZ",
    "800": "UG",
    "804": "UA",
    "581": "UM",
    "858": "UY",
    "840": "US",
    "860": "UZ",
    "336": "VA",
    "670": "VC",
    "862": "VE",
    "092": "VG",
    "850": "VI",
    "704": "VN",
    "548": "VU",
    "876": "WF",
    "882": "WS",
    "000": "XX",
    "887": "YE",
    "710": "ZA",
    "894": "ZM",
    "716": "ZW"
}
